// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBV8AP1znZaY0kVYpxS7EQfeSBWiVLs7nY',
    appId: '1:534424149070:web:0ad88858ba1def033ef71f',
    messagingSenderId: '534424149070',
    projectId: 'geo-guardian',
    authDomain: 'geo-guardian.firebaseapp.com',
    databaseURL: 'https://geo-guardian-default-rtdb.firebaseio.com',
    storageBucket: 'geo-guardian.firebasestorage.app',
    measurementId: 'G-W4Q457DS9C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyILxPDsc-cqlNvfMAUipvIJSxqW2SavE',
    appId: '1:534424149070:android:0d0bd7334c59b98f3ef71f',
    messagingSenderId: '534424149070',
    projectId: 'geo-guardian',
    databaseURL: 'https://geo-guardian-default-rtdb.firebaseio.com',
    storageBucket: 'geo-guardian.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFrGf0TkqoyLmwinK-biVWBxoqzdFJNDM',
    appId: '1:534424149070:ios:058d62f90f6a875a3ef71f',
    messagingSenderId: '534424149070',
    projectId: 'geo-guardian',
    databaseURL: 'https://geo-guardian-default-rtdb.firebaseio.com',
    storageBucket: 'geo-guardian.firebasestorage.app',
    iosBundleId: 'com.gg.geoGuardian',
  );
}
